### ISSUE TITLE
插件似乎失效了

### ISSUE THREAD

**Issue by VAHua** [wlm3201/nonebot-plugin-mcpic#1]
调用此插件，无法发送图片出来
```
04-02 16:13:59 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
04-02 16:13:59 [DEBUG] nonebot | Running CalledAPI hooks...
04-02 16:13:59 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mcpic, lineno=20) running complet
e
04-02 16:13:59 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mcpic, lineno=20) failed
.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Program Files (x86)\python\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_reboot\reloader.py", line 27
, in _run
    _nb_run(*args, **kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\__init__.py", line 334, in run     
    get_driver().run(*args, **kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\drivers\fastapi.py", line 186, in r
un
    uvicorn.run(
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\uvicorn\server.py", line 60, in run        
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Program Files (x86)\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Program Files (x86)\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Program Files (x86)\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\message.py", line 476, in check_and
_run_matcher
    await _run_matcher(
> File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\message.py", line 428, in _run_matc
her
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\matcher\matcher.py", line 
842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\matcher\matcher.py", line 
817, in simple_run
    await handler(
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\dependencies\__init__.py", line 106
, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot_plugin_mcpic\__init__.py", line 59, in handle_m
cpic
    await mcpic.finish(segs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\matcher\matcher.py", line 
574, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\matcher\matcher.py", line 
558, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\adapters\onebot\v11\bot.py", line 2
28, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\adapters\onebot\v11\bot.py", line 1
81, in send
    return await bot.send_msg(**params)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\adapter\bot.py", line 122,
 in call_api
    raise exception
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\adapter\bot.py", line 97, 
in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\adapters\onebot\v11\adapter.py", li
ne 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot\adapters\onebot\v11\utils.py", line
 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, mess
age='文件异常，大小为0', wording='文件异常，大小为0', echo='1')
```

**Comment by wlm3201** [comment]
试试能ping通 192.229.233.50 吗
如果不行，试试
199.232.56.159
146.75.120.159
192.229.237.101
93.184.220.70
如果有，把__init__.py里的192.229.233.50改成能ping通的ip

**Comment by VAHua** [comment]
可以了，感谢大佬。当时应该是我网不稳定
![image](https://github.com/wlm3201/nonebot-plugin-mcpic/assets/129832780/8f16fade-c69d-44fb-aed0-c33cc4439f58)
![image](https://github.com/wlm3201/nonebot-plugin-mcpic/assets/129832780/bb116f90-2c6b-4de7-97ff-ce193af70bb2)
